input:
  nats_jetstream:
    urls:
      - nats://nats:4222
    stream: orders
    subject: orders.created
    durable: ${NATS_DURABLE}

pipeline:
  processors:
    - mapping: |
        root = if (this.key | "") != "" && (this.value | "") != "" {
          { this.key: this.value }
        } else {
          deleted()
        }

output:
  redis_hash:
    url: tcp://${REDIS_HOST}:6379
    key: orders-created-kv
    walk_json_object: true
